# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $crud: '@App\Service\GenericCrudService'

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'
